require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const User = require('../models/User');
const Category = require('../models/Category');
const Product = require('../models/Product');

const users = [
  { name: 'Admin User', email: 'admin@ecommerce.com', password: 'admin123', role: 'admin' },
  { name: 'John Doe', email: 'john@example.com', password: 'user123', role: 'user' },
];

const categories = [
  { name: 'Electronics', image: '/images/techImages/image-22.png', slug: 'electronics' },
  { name: 'Clothing', image: '/images/clothImages/image-24.png', slug: 'clothing' },
  { name: 'Home & Garden', image: '/images/interiorImages/image-87.png', slug: 'home-garden' },
  { name: 'Books', image: '/images/bookImages/image-36.png', slug: 'books' },
];

// Image paths reference files copied to frontend/public/images/
const img = (folder, file) => [`/images/${folder}/${file}`];

// Standard 3-tier pricing pattern matching the Figma design (50-100 / 100-700 / 700+ pcs)
const tiers = (basePrice) => ([
  { minQty: 50, maxQty: 100, price: +(basePrice * 1.25).toFixed(2), label: '50-100 pcs' },
  { minQty: 100, maxQty: 700, price: +(basePrice * 1.15).toFixed(2), label: '100-700 pcs' },
  { minQty: 700, maxQty: null, price: basePrice, label: '700+ pcs' },
]);

const rawProducts = [
  // ===== ELECTRONICS (techImages) =====
  {
    name: 'GoPro HERO6 4K Action Camera - Black',
    description: 'Capture every adventure in stunning 4K. Waterproof, image stabilization, wide-angle lens, and 2-inch touchscreen. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 998.00, originalPrice: 1128.00, discount: 12,
    categoryName: 'Electronics', brand: 'GoPro',
    stock: 45, isFeatured: true, isVerified: true, rating: 4.2, numReviews: 154, sold: 154,
    images: img('techImages', 'image-22.png'),
    tags: ['camera', '4k', 'action', 'waterproof'],
    specifications: { Model: '#8786867', Style: 'Classic style', Certificate: 'ISO-898921212', Size: '34mm x 450mm x 19mm', Memory: '36GB RAM' },
    features: ['Some great feature name here', 'Lorem ipsum dolor sit amet, consectetur', 'Duis aute irure dolor in reprehenderit', 'Some great feature name here'],
    shipping: 'Worldwide shipping', sellerName: 'GoPro Official Store', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Canon Camera EOS 2000, Black 10x zoom',
    description: 'Professional DSLR camera with 10x optical zoom, full HD recording, and intuitive controls for beginners and enthusiasts.',
    price: 998.00, originalPrice: 1128.00, discount: 12,
    categoryName: 'Electronics', brand: 'Canon',
    stock: 30, isFeatured: true, isVerified: true, rating: 3.0, numReviews: 154, sold: 154,
    images: img('techImages', 'image-23.png'),
    tags: ['camera', 'dslr', 'canon', 'zoom'],
    specifications: { Model: '#2000D', Style: 'DSLR', Certificate: 'ISO-898921212', Zoom: '10x optical' },
    features: ['Full HD video recording', 'Lorem ipsum dolor sit amet, consectetur', 'Duis aute irure dolor in reprehenderit'],
    shipping: 'Worldwide shipping', sellerName: 'Canon Official Store', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Smartphone Pro Max - Midnight Red',
    description: 'Flagship smartphone with edge-to-edge display, triple camera system, and all-day battery life.',
    price: 99.50, originalPrice: 1128.00, discount: 91,
    categoryName: 'Electronics', brand: 'Apple',
    stock: 60, isFeatured: true, isVerified: true, rating: 4.3, numReviews: 154, sold: 280,
    images: img('techImages', 'image-28.png'),
    tags: ['smartphone', 'apple', 'mobile'],
    specifications: { Model: '#A2483', Display: '6.1 inch OLED', Storage: '128GB', Color: 'Midnight Red' },
    features: ['Triple camera system', 'All-day battery life', 'Edge-to-edge display'],
    shipping: 'Worldwide shipping', sellerName: 'Apple Authorized Reseller', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Smartphone Pro Max - Pacific Blue',
    description: 'Flagship smartphone with edge-to-edge display, triple camera system, and all-day battery life. Available in stunning Pacific Blue finish.',
    price: 99.50, originalPrice: 1128.00, discount: 91,
    categoryName: 'Electronics', brand: 'Apple',
    stock: 55, isFeatured: false, isVerified: true, rating: 3.0, numReviews: 89, sold: 210,
    images: img('techImages', 'image-29.png'),
    tags: ['smartphone', 'apple', 'mobile'],
    specifications: { Model: '#A2484', Display: '6.1 inch OLED', Storage: '256GB', Color: 'Pacific Blue' },
    features: ['Triple camera system', 'All-day battery life'],
    shipping: 'Worldwide shipping', sellerName: 'Apple Authorized Reseller', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Tablet Pro 11" - Space Gray',
    description: 'Powerful tablet with 11-inch Liquid Retina display, all-day battery, and support for stylus and keyboard accessories.',
    price: 99.50, originalPrice: 1128.00, discount: 91,
    categoryName: 'Electronics', brand: 'TechPro',
    stock: 25, isFeatured: true, isVerified: true, rating: 4.5, numReviews: 154, sold: 95,
    images: img('techImages', 'image-32.png'),
    tags: ['tablet', 'electronics', 'touchscreen'],
    specifications: { Display: '11-inch Liquid Retina', Storage: '256GB', Battery: '10 hours' },
    features: ['Supports stylus and keyboard', 'All-day battery life'],
    shipping: 'Worldwide shipping', sellerName: 'TechPro Store', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Ultra-Slim Laptop 15" - Silver',
    description: 'Lightweight high-performance laptop with stunning display, fast SSD storage, and all-day battery life.',
    price: 998.00, originalPrice: 1128.00, discount: 12,
    categoryName: 'Electronics', brand: 'TechPro',
    stock: 15, isFeatured: true, isVerified: true, rating: 4.1, numReviews: 154, sold: 178,
    images: img('techImages', 'image-33.png'),
    tags: ['laptop', 'computer', 'electronics'],
    specifications: { Processor: 'Octa-core 3.2GHz', RAM: '16GB', Storage: '512GB SSD', Display: '15.6-inch FHD' },
    features: ['Fast SSD storage', 'Lightweight design'],
    shipping: 'Worldwide shipping', sellerName: 'TechPro Store', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Smart Watch Series 5 - Silver',
    description: 'Advanced smartwatch with health monitoring, GPS, always-on display, and water resistance.',
    price: 998.00, originalPrice: 1128.00, discount: 12,
    categoryName: 'Electronics', brand: 'TechFit',
    stock: 40, isFeatured: true, isVerified: true, rating: 4.1, numReviews: 154, sold: 320,
    images: img('techImages', 'image-34.png'),
    tags: ['smartwatch', 'fitness', 'wearable'],
    specifications: { Display: '1.78-inch AMOLED', Battery: '18 hours', 'Water resistance': '50m' },
    features: ['Health monitoring', 'Built-in GPS'],
    shipping: 'Worldwide shipping', sellerName: 'TechFit Store', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Premium Headphones - White',
    description: 'Over-ear headphones with active noise cancellation, premium sound quality, and plush comfort for extended listening sessions.',
    price: 998.00, originalPrice: 1128.00, discount: 12,
    categoryName: 'Electronics', brand: 'SoundWave',
    stock: 50, isFeatured: false, isVerified: true, rating: 4.1, numReviews: 154, sold: 412,
    images: img('techImages', 'image-35.png'),
    tags: ['headphones', 'audio', 'wireless'],
    specifications: { Type: 'Over-ear, wireless', Battery: '30 hours', 'Noise cancellation': 'Active' },
    features: ['Active noise cancellation', 'Plush comfort padding'],
    shipping: 'Worldwide shipping', sellerName: 'SoundWave Store', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Smartphone Wave - Aurora',
    description: 'Modern smartphone featuring a sleek gradient finish, high-resolution display, and powerful processor for seamless multitasking.',
    price: 99.50, originalPrice: 1128.00, discount: 91,
    categoryName: 'Electronics', brand: 'Xiaomi',
    stock: 70, isFeatured: false, isVerified: true, rating: 4.0, numReviews: 154, sold: 540,
    images: img('techImages', 'image-86.png'),
    tags: ['smartphone', 'xiaomi', 'mobile'],
    specifications: { Model: 'Redmi 8', Display: '6.22-inch IPS', Storage: '64GB' },
    features: ['High-resolution display', 'Powerful processor'],
    shipping: 'Worldwide shipping', sellerName: 'Xiaomi Official Store', sellerLocation: 'Germany, Berlin',
  },

  // ===== CLOTHING (clothImages) =====
  {
    name: 'Mens Long Sleeve T-shirt Cotton Base Layer Slim Muscle',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    price: 78.00, originalPrice: 98.00, discount: 20,
    categoryName: 'Clothing', brand: 'Guanjoi Trading LLC',
    stock: 200, isFeatured: true, isVerified: true, rating: 4.0, numReviews: 32, sold: 154,
    images: img('clothImages', 'image-24.png'),
    tags: ['t-shirt', 'men', 'cotton', 'summer'],
    specifications: { Model: '#8786867', Style: 'Classic style', Certificate: 'ISO-898921212', Size: '34mm x 450mm x 19mm', Memory: '36GB RAM' },
    features: ['Some great feature name here', 'Lorem ipsum dolor sit amet, consectetur', 'Duis aute irure dolor in reprehenderit', 'Some great feature name here'],
    shipping: 'Worldwide shipping', sellerName: 'Guanjoi Trading LLC', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'T-shirts with multiple colors, for men and lady',
    description: 'Premium quality t-shirts available in multiple colors for both men and women. Soft, breathable fabric perfect for everyday wear.',
    price: 78.99, originalPrice: 99.00, discount: 21,
    categoryName: 'Clothing', brand: 'Artel Market',
    stock: 150, isFeatured: true, isVerified: true, rating: 4.2, numReviews: 88, sold: 320,
    images: img('clothImages', 'image-25.png'),
    tags: ['t-shirt', 'unisex', 'casual'],
    specifications: { Size: 'Medium', Color: 'Blue', Material: 'Cotton blend' },
    features: ['Breathable fabric', 'Multiple colors available'],
    shipping: 'Worldwide shipping', sellerName: 'Artel Market', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Men Blazers Sets Elegant Formal',
    description: 'Elegant formal blazer set for men, perfect for business meetings and special occasions. Tailored fit with premium fabric.',
    price: 7.00, originalPrice: 99.50, discount: 93,
    categoryName: 'Clothing', brand: 'StyleCo',
    stock: 80, isFeatured: true, isVerified: true, rating: 4.4, numReviews: 56, sold: 142,
    images: img('clothImages', 'image-26.png'),
    tags: ['blazer', 'formal', 'men'],
    specifications: { Material: 'Wool blend', Fit: 'Slim fit', Occasion: 'Formal' },
    features: ['Tailored fit', 'Premium fabric'],
    shipping: 'Worldwide shipping', sellerName: 'StyleCo', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Brown Winter Coat Medium Size',
    description: 'Warm and stylish winter coat with faux fur hood, perfect for cold weather. Durable construction with insulated lining.',
    price: 10.30, originalPrice: 25.00, discount: 59,
    categoryName: 'Clothing', brand: 'WinterWear',
    stock: 60, isFeatured: false, isVerified: true, rating: 4.3, numReviews: 41, sold: 98,
    images: img('clothImages', 'image-30.png'),
    tags: ['coat', 'winter', 'jacket'],
    specifications: { Size: 'Medium', Material: 'Polyester with faux fur', Season: 'Winter' },
    features: ['Faux fur hood', 'Insulated lining'],
    shipping: 'Worldwide shipping', sellerName: 'WinterWear', sellerLocation: 'Germany, Berlin',
  },
  {
    name: "New Summer Men's Castrol T-Shirts",
    description: 'Lightweight summer t-shirts with classic crew neck design. Breathable fabric keeps you cool all day long.',
    price: 7.00, originalPrice: 99.50, discount: 93,
    categoryName: 'Clothing', brand: 'CastrolWear',
    stock: 180, isFeatured: false, isVerified: true, rating: 4.1, numReviews: 67, sold: 256,
    images: img('clothImages', 'Bitmap.png'),
    tags: ['t-shirt', 'summer', 'men'],
    specifications: { Material: '100% Cotton', Fit: 'Regular fit' },
    features: ['Classic crew neck', 'Breathable fabric'],
    shipping: 'Worldwide shipping', sellerName: 'CastrolWear', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Leather Wallet - Travel Edition',
    description: 'Genuine leather wallet with multiple card slots and bill compartments. Slim profile fits comfortably in any pocket.',
    price: 34.00, originalPrice: 50.00, discount: 32,
    categoryName: 'Clothing', brand: 'LuxeCarry',
    stock: 95, isFeatured: false, isVerified: true, rating: 4.6, numReviews: 112, sold: 410,
    images: img('clothImages', 'Bitmap-1.png'),
    tags: ['wallet', 'leather', 'accessories'],
    specifications: { Material: 'Genuine leather', 'Card slots': '8' },
    features: ['Genuine leather', 'Slim profile'],
    shipping: 'Worldwide shipping', sellerName: 'LuxeCarry', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Jeans Bag for Travel for Men',
    description: 'Durable denim travel bag with reinforced straps and ample storage space for weekend getaways or daily commutes.',
    price: 99.00, originalPrice: 150.00, discount: 34,
    categoryName: 'Clothing', brand: 'RoamSafe',
    stock: 45, isFeatured: false, isVerified: true, rating: 4.4, numReviews: 78, sold: 165,
    images: img('clothImages', '2-1.png'),
    tags: ['bag', 'travel', 'denim'],
    specifications: { Material: 'Denim', Capacity: '30L' },
    features: ['Reinforced straps', 'Ample storage'],
    shipping: 'Worldwide shipping', sellerName: 'RoamSafe', sellerLocation: 'Germany, Berlin',
  },

  // ===== HOME & GARDEN (interiorImages) =====
  {
    name: 'Soft Accent Chair - Beige',
    description: 'Comfortable upholstered accent chair, perfect for living rooms and reading corners. Sturdy wooden legs with soft cushioning.',
    price: 19.00, originalPrice: 35.00, discount: 46,
    categoryName: 'Home & Garden', brand: 'HomeComfort',
    stock: 30, isFeatured: true, isVerified: true, rating: 4.5, numReviews: 64, sold: 120,
    images: img('interiorImages', 'image-87.png'),
    tags: ['chair', 'furniture', 'living room'],
    specifications: { Material: 'Fabric upholstery, wood legs', Color: 'Beige' },
    features: ['Sturdy wooden legs', 'Soft cushioning'],
    shipping: 'Worldwide shipping', sellerName: 'HomeComfort', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Modern Table Lamp - Ceramic',
    description: 'Elegant ceramic table lamp with fabric shade, adds warm ambient lighting to any room. Perfect for bedside tables and desks.',
    price: 19.00, originalPrice: 30.00, discount: 37,
    categoryName: 'Home & Garden', brand: 'HomeComfort',
    stock: 55, isFeatured: true, isVerified: true, rating: 4.3, numReviews: 53, sold: 210,
    images: img('interiorImages', 'image-88.png'),
    tags: ['lamp', 'lighting', 'decor'],
    specifications: { Material: 'Ceramic, fabric shade', 'Bulb type': 'E27' },
    features: ['Warm ambient lighting', 'Elegant design'],
    shipping: 'Worldwide shipping', sellerName: 'HomeComfort', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Kitchen Dishware Set - Blue',
    description: 'Complete kitchen dishware set including plates, bowls, and serving dishes. Microwave and dishwasher safe.',
    price: 19.00, originalPrice: 28.00, discount: 32,
    categoryName: 'Home & Garden', brand: 'KitchenPro',
    stock: 70, isFeatured: false, isVerified: true, rating: 4.4, numReviews: 89, sold: 305,
    images: img('interiorImages', 'image-89.png'),
    tags: ['kitchen', 'dishes', 'tableware'],
    specifications: { Pieces: '16-piece set', Material: 'Ceramic' },
    features: ['Microwave safe', 'Dishwasher safe'],
    shipping: 'Worldwide shipping', sellerName: 'KitchenPro', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Terracotta Decorative Vase',
    description: 'Handcrafted terracotta vase with natural finish, perfect for dried flowers or as a standalone decorative piece.',
    price: 19.00, originalPrice: 32.00, discount: 41,
    categoryName: 'Home & Garden', brand: 'EarthCraft',
    stock: 40, isFeatured: false, isVerified: true, rating: 4.2, numReviews: 37, sold: 88,
    images: img('interiorImages', 'image-90.png'),
    tags: ['vase', 'decor', 'terracotta'],
    specifications: { Material: 'Terracotta clay', Height: '30cm' },
    features: ['Handcrafted', 'Natural finish'],
    shipping: 'Worldwide shipping', sellerName: 'EarthCraft', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Stand Mixer - Professional Grade',
    description: 'Powerful kitchen stand mixer with multiple attachments for baking, mixing, and kneading. 10 speed settings.',
    price: 100.00, originalPrice: 150.00, discount: 33,
    categoryName: 'Home & Garden', brand: 'ChefElite',
    stock: 22, isFeatured: true, isVerified: true, rating: 4.7, numReviews: 145, sold: 412,
    images: img('interiorImages', 'image-91.png'),
    tags: ['mixer', 'kitchen', 'baking'],
    specifications: { Capacity: '5L bowl', Power: '600W', Speeds: '10' },
    features: ['Multiple attachments', '10 speed settings'],
    shipping: 'Worldwide shipping', sellerName: 'ChefElite', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Compact Blender - Personal Size',
    description: 'Personal blender perfect for smoothies and shakes. Compact design with travel-friendly cup and lid.',
    price: 39.00, originalPrice: 55.00, discount: 29,
    categoryName: 'Home & Garden', brand: 'KitchenPro',
    stock: 65, isFeatured: false, isVerified: true, rating: 4.3, numReviews: 92, sold: 380,
    images: img('interiorImages', 'image-92.png'),
    tags: ['blender', 'kitchen', 'smoothie'],
    specifications: { Capacity: '600ml', Power: '300W' },
    features: ['Travel-friendly cup', 'Compact design'],
    shipping: 'Worldwide shipping', sellerName: 'KitchenPro', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Leather Storage Organizer - Brown',
    description: 'Multi-slot leather desktop organizer for documents, mail, and accessories. Adds an elegant touch to any home office.',
    price: 19.00, originalPrice: 28.00, discount: 32,
    categoryName: 'Home & Garden', brand: 'HomeComfort',
    stock: 35, isFeatured: false, isVerified: true, rating: 4.1, numReviews: 24, sold: 76,
    images: img('interiorImages', 'image-93.png'),
    tags: ['organizer', 'office', 'storage'],
    specifications: { Material: 'PU leather', Slots: '3' },
    features: ['Multi-slot design', 'Elegant touch'],
    shipping: 'Worldwide shipping', sellerName: 'HomeComfort', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Premium Coffee Maker - Stainless Steel',
    description: 'Programmable coffee maker with thermal carafe, brew strength control, and auto shut-off. Brews up to 12 cups.',
    price: 10.00, originalPrice: 25.00, discount: 60,
    categoryName: 'Home & Garden', brand: 'BrewMaster',
    stock: 50, isFeatured: true, isVerified: true, rating: 4.5, numReviews: 178, sold: 520,
    images: img('interiorImages', 'image-94.png'),
    tags: ['coffee', 'kitchen', 'appliance'],
    specifications: { Capacity: '12 cups', Material: 'Stainless steel' },
    features: ['Auto shut-off', 'Thermal carafe'],
    shipping: 'Worldwide shipping', sellerName: 'BrewMaster', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Decorative Plant Pot - Round',
    description: 'Stylish ceramic plant pot with drainage hole, perfect for indoor plants and herbs. Adds greenery to any space.',
    price: 10.30, originalPrice: 18.00, discount: 43,
    categoryName: 'Home & Garden', brand: 'EarthCraft',
    stock: 80, isFeatured: false, isVerified: true, rating: 4.0, numReviews: 45, sold: 190,
    images: img('interiorImages', 'rasm.png'),
    tags: ['planter', 'pot', 'garden'],
    specifications: { Material: 'Ceramic', Diameter: '20cm' },
    features: ['Drainage hole', 'Stylish design'],
    shipping: 'Worldwide shipping', sellerName: 'EarthCraft', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Modern Sofa Chair - Two Seater',
    description: 'Contemporary two-seater sofa chair with premium upholstery and solid wood frame. A stylish addition to your living space.',
    price: 99.00, originalPrice: 150.00, discount: 34,
    categoryName: 'Home & Garden', brand: 'HomeComfort',
    stock: 12, isFeatured: true, isVerified: true, rating: 4.6, numReviews: 58, sold: 95,
    images: img('interiorImages', 'rasm-1.png'),
    tags: ['sofa', 'furniture', 'living room'],
    specifications: { Material: 'Fabric, solid wood frame', Seating: '2-seater' },
    features: ['Premium upholstery', 'Solid wood frame'],
    shipping: 'Worldwide shipping', sellerName: 'HomeComfort', sellerLocation: 'Germany, Berlin',
  },

  // ===== BOOKS (bookImages) =====
  {
    name: 'The Art of Modern Living - Hardcover',
    description: 'A beautifully illustrated guide to minimalist living and interior design philosophy. Perfect coffee table book for design enthusiasts.',
    price: 12.50, originalPrice: 20.00, discount: 38,
    categoryName: 'Books', brand: 'PenPress',
    stock: 100, isFeatured: true, isVerified: true, rating: 4.6, numReviews: 210, sold: 540,
    images: img('bookImages', 'image-36.png'),
    tags: ['book', 'design', 'hardcover'],
    specifications: { Format: 'Hardcover', Pages: '320', Language: 'English' },
    features: ['Beautifully illustrated', 'Coffee table book'],
    shipping: 'Worldwide shipping', sellerName: 'PenPress', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Business Strategy Essentials - Paperback',
    description: 'A comprehensive guide to modern business strategy, covering case studies and practical frameworks for entrepreneurs.',
    price: 9.99, originalPrice: 16.00, discount: 38,
    categoryName: 'Books', brand: 'PenPress',
    stock: 120, isFeatured: false, isVerified: true, rating: 4.4, numReviews: 156, sold: 412,
    images: img('bookImages', 'image-37.png'),
    tags: ['book', 'business', 'paperback'],
    specifications: { Format: 'Paperback', Pages: '280', Language: 'English' },
    features: ['Case studies included', 'Practical frameworks'],
    shipping: 'Worldwide shipping', sellerName: 'PenPress', sellerLocation: 'Germany, Berlin',
  },
  {
    name: "Children's Picture Book Collection",
    description: 'A delightful collection of illustrated stories for young readers, fostering imagination and a love for reading.',
    price: 14.99, originalPrice: 24.00, discount: 38,
    categoryName: 'Books', brand: 'KidsRead',
    stock: 90, isFeatured: true, isVerified: true, rating: 4.8, numReviews: 312, sold: 680,
    images: img('bookImages', 'image-38.png'),
    tags: ['book', 'children', 'illustrated'],
    specifications: { Format: 'Hardcover', 'Age range': '3-8 years' },
    features: ['Illustrated stories', 'Fosters imagination'],
    shipping: 'Worldwide shipping', sellerName: 'KidsRead', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Science Fiction Anthology - Volume 1',
    description: 'A curated collection of award-winning science fiction short stories from acclaimed authors around the world.',
    price: 11.50, originalPrice: 18.00, discount: 36,
    categoryName: 'Books', brand: 'PenPress',
    stock: 75, isFeatured: false, isVerified: true, rating: 4.3, numReviews: 98, sold: 245,
    images: img('bookImages', 'image-39.png'),
    tags: ['book', 'fiction', 'anthology'],
    specifications: { Format: 'Paperback', Pages: '410' },
    features: ['Award-winning stories', 'Curated collection'],
    shipping: 'Worldwide shipping', sellerName: 'PenPress', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Cookbook: World Cuisines Made Easy',
    description: 'Step-by-step recipes from cuisines around the globe, with full-color photography and beginner-friendly instructions.',
    price: 16.99, originalPrice: 27.00, discount: 37,
    categoryName: 'Books', brand: 'KitchenPro',
    stock: 60, isFeatured: true, isVerified: true, rating: 4.7, numReviews: 188, sold: 390,
    images: img('bookImages', 'image-40.png'),
    tags: ['book', 'cookbook', 'recipes'],
    specifications: { Format: 'Hardcover', Pages: '256' },
    features: ['Full-color photography', 'Beginner-friendly'],
    shipping: 'Worldwide shipping', sellerName: 'KitchenPro', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'Self-Improvement Journal & Planner',
    description: 'A guided journal combining habit tracking, goal setting, and reflection prompts for personal growth.',
    price: 8.99, originalPrice: 15.00, discount: 40,
    categoryName: 'Books', brand: 'PenPress',
    stock: 150, isFeatured: false, isVerified: true, rating: 4.5, numReviews: 134, sold: 470,
    images: img('bookImages', 'Image.png'),
    tags: ['book', 'journal', 'planner'],
    specifications: { Format: 'Spiral-bound', Pages: '180' },
    features: ['Habit tracking', 'Goal setting prompts'],
    shipping: 'Worldwide shipping', sellerName: 'PenPress', sellerLocation: 'Germany, Berlin',
  },
  {
    name: 'History of Ancient Civilizations',
    description: 'An in-depth exploration of ancient civilizations, their cultures, achievements, and lasting impact on the modern world.',
    price: 13.99, originalPrice: 22.00, discount: 36,
    categoryName: 'Books', brand: 'PenPress',
    stock: 55, isFeatured: false, isVerified: true, rating: 4.6, numReviews: 76, sold: 198,
    images: img('bookImages', 'Image-1.png'),
    tags: ['book', 'history', 'education'],
    specifications: { Format: 'Hardcover', Pages: '450' },
    features: ['In-depth exploration', 'Educational'],
    shipping: 'Worldwide shipping', sellerName: 'PenPress', sellerLocation: 'Germany, Berlin',
  },
];

const seedDB = async () => {
  await connectDB();
  await User.deleteMany();
  await Category.deleteMany();
  await Product.deleteMany();

  const createdUsers = await User.insertMany(users);
  console.log(`✅ ${createdUsers.length} users seeded`);

  const createdCategories = await Category.insertMany(categories);
  console.log(`✅ ${createdCategories.length} categories seeded`);
  const categoryMap = {};
  createdCategories.forEach(c => { categoryMap[c.name] = c._id; });

  const products = rawProducts.map(({ categoryName, ...p }) => ({
    ...p,
    category: categoryMap[categoryName],
    pricingTiers: tiers(p.price),
  }));

  const createdProducts = await Product.insertMany(products);
  console.log(`✅ ${createdProducts.length} products seeded`);

  console.log('\n🔑 Login credentials:');
  console.log('   Admin: admin@ecommerce.com / admin123');
  console.log('   User:  john@example.com   / user123\n');

  process.exit(0);
};

seedDB().catch((err) => { console.error(err); process.exit(1); });
